/** The visual lab's (A96) own strings: a hidden page, so they stay out of site.ts. */
export const TEXT = {
  en: {
    title: 'Visual lab',
    hide: 'Hide',
    show: 'Show lab',
    meter: 'Frame meter',
    fps: 'fps',
    low: '1% low',
    longest: 'longest',
    bench: 'Benchmark (5 s)',
    running: 'Running…',
    benchPan: 'Scripted pan and zoom',
    benchOrbit: 'Scripted orbit',
    average: 'average',
    active: 'Active',
    defaults: 'all defaults (today)',
    curve: 'Edge curve',
    haystack: 'Straight (haystack, today)',
    bezier: 'Bezier',
    unbundled: 'Curved (unbundled bezier)',
    strength: 'Curve strength',
    gradient: 'Gradient edges (domain to domain)',
    flow: 'One-way flow',
    dots: 'Overlay dots (today)',
    dashes: 'Marching dashes (old)',
    none: 'None',
    speed: 'Flow speed',
    hover: 'Hover restyle',
    hoverNow: 'Visible map (today)',
    hoverOld: 'Every element, with fades (old)',
    glow: 'Node glow',
    all: 'Show all relationships',
    labels: 'Labels',
    labelsNone: 'None',
    labelsHubs: 'Hubs only',
    labelsNow: 'Culled (today)',
    labelsAll: 'All (overlapping)',
    texture: 'Snapshot while panning (today)',
    textureNote: 'The benchmark moves the view directly, so it always draws full frames.',
    links: 'Link geometry',
    lines: 'Merged lines (today)',
    tubes: 'Tube and cone per link (old)',
    curvature: 'Link curvature',
    comets: 'Comets (today)',
    particles: 'Per-link particles (old)',
    glow3: 'Glow',
    cloud: 'Point cloud (today)',
    sprites: 'Sprite per term (old)',
    bloom: 'Bloom',
    spin: 'Auto-rotate',
    fog: 'Fog',
    spacing: 'Node spacing',
    emph: 'Emphasis by importance',
    emphOff: 'Off (today)',
    emphOpacity: 'Opacity',
    emphColour: 'Colour (saturation, lightness)',
    emphWidth: 'Line width',
    emphCombined: 'Combined',
    spread: 'Importance spread',
    emphNote:
      'Importance = type rank (requires, kind of, part of first; used with last) × the edge weight.',
    emphNote3d: 'Lines are one pixel wide: width shows on tubes only.',
    bloomLight: 'Bloom applies to the night map only.',
    layout: 'Layout (relayout)',
    mindist: 'Minimum node distance',
    sub: 'Sub-domain clusters',
    clabels: 'Faint cluster names',
    toneTitle: 'Cream map contrast',
    toneNote: 'Applies on the light theme (switch it in the header); live preview.',
    nodeSat: 'Term saturation',
    nodeLight: 'Term lightness',
    edgeDark: 'Edge darkness',
    edgeAlpha: 'Edge opacity',
    shadow: 'Shadow strength',
    labelWeight: 'Label weight',
    labelHalo: 'Label halo',
    copy: 'Copy values',
    copied: 'Copied',
  },
  da: {
    title: 'Visuelt laboratorium',
    hide: 'Skjul',
    show: 'Vis lab',
    meter: 'Billedmåler',
    fps: 'fps',
    low: '1% lav',
    longest: 'længste',
    bench: 'Benchmark (5 s)',
    running: 'Kører…',
    benchPan: 'Scriptet panorering og zoom',
    benchOrbit: 'Scriptet kredsløb',
    average: 'gennemsnit',
    active: 'Aktive',
    defaults: 'alle standarder (i dag)',
    curve: 'Kantkurve',
    haystack: 'Lige (haystack, i dag)',
    bezier: 'Bezier',
    unbundled: 'Buet (unbundled bezier)',
    strength: 'Kurvestyrke',
    gradient: 'Gradientkanter (domæne til domæne)',
    flow: 'Envejsflow',
    dots: 'Prikker i overlag (i dag)',
    dashes: 'Marcherende streger (gammel)',
    none: 'Ingen',
    speed: 'Flowhastighed',
    hover: 'Hover-omstil',
    hoverNow: 'Synligt kort (i dag)',
    hoverOld: 'Alle elementer, med toninger (gammel)',
    glow: 'Nodeglød',
    all: 'Vis alle relationer',
    labels: 'Etiketter',
    labelsNone: 'Ingen',
    labelsHubs: 'Kun knudepunkter',
    labelsNow: 'Udtyndet (i dag)',
    labelsAll: 'Alle (overlappende)',
    texture: 'Øjebliksbillede under panorering (i dag)',
    textureNote: 'Benchmarken flytter visningen direkte, så den tegner altid hele billeder.',
    links: 'Forbindelsesgeometri',
    lines: 'Samlede linjer (i dag)',
    tubes: 'Rør og kegle pr. forbindelse (gammel)',
    curvature: 'Forbindelseskrumning',
    comets: 'Kometer (i dag)',
    particles: 'Partikler pr. forbindelse (gammel)',
    glow3: 'Glød',
    cloud: 'Punktsky (i dag)',
    sprites: 'Sprite pr. begreb (gammel)',
    bloom: 'Bloom',
    spin: 'Autorotation',
    fog: 'Tåge',
    spacing: 'Nodeafstand',
    emph: 'Fremhævning efter vigtighed',
    emphOff: 'Fra (i dag)',
    emphOpacity: 'Gennemsigtighed',
    emphColour: 'Farve (mætning, lyshed)',
    emphWidth: 'Stregbredde',
    emphCombined: 'Kombineret',
    spread: 'Vigtighedsspredning',
    emphNote:
      'Vigtighed = typens rang (kræver, er en slags, er del af først; bruges med sidst) × kantens vægt.',
    emphNote3d: 'Linjer er én pixel brede: bredde ses kun på rør.',
    bloomLight: 'Bloom virker kun på natkortet.',
    layout: 'Layout (nyt layout)',
    mindist: 'Mindste nodeafstand',
    sub: 'Underdomæne-klynger',
    clabels: 'Svage klyngenavne',
    toneTitle: 'Kontrast på det lyse kort',
    toneNote: 'Gælder det lyse tema (skift det i sidehovedet); vises med det samme.',
    nodeSat: 'Begrebsmætning',
    nodeLight: 'Begrebslyshed',
    edgeDark: 'Kantmørke',
    edgeAlpha: 'Kantgennemsigtighed',
    shadow: 'Skyggestyrke',
    labelWeight: 'Etiketvægt',
    labelHalo: 'Etiketkant',
    copy: 'Kopiér værdier',
    copied: 'Kopieret',
  },
};
export type Text = (typeof TEXT)['en'];
