/**
 * Site chrome: the header nav, theme and language menus, footer, 404 page.
 * A slice of `UI` (site.ts), which merges every area into one table per language.
 */
export const UI_LAYOUT = {
  en: {
    tagline: 'A bilingual technical dictionary that reads as a knowledge graph.',
    index: 'Index',
    compare: 'Compare',
    study: 'Study',
    explorer: 'Explorer',
    timeline: 'Timeline',
    sourceCode: 'Source',
    privacy: 'Privacy',
    home: 'Home',
    menu: 'Menu',
    skipToContent: 'Skip to content',
    backToTop: 'Back to top',
    copyLink: 'Copy link',
    linkCopied: 'Link copied',
    breadcrumb: 'Breadcrumb',
    theme: 'Theme',
    themeSystem: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    language: 'Language',
    langSuggest: 'This page is available in English.',
    langSwitch: 'Switch to English',
    langKeep: 'No thanks',
    notFoundTitle: 'Page not found',
    notFoundBody: 'The page you asked for does not exist - it may have moved.',
    notFoundHome: 'Go to the English home page',
    loading: 'Loading…',
  },
  da: {
    tagline: 'En tosproget teknisk ordbog, der læses som en vidensgraf.',
    index: 'Indeks',
    compare: 'Sammenlign',
    study: 'Øv',
    explorer: 'Udforsk',
    timeline: 'Tidslinje',
    sourceCode: 'Kildekode',
    privacy: 'Privatliv',
    home: 'Forside',
    menu: 'Menu',
    skipToContent: 'Gå til indhold',
    backToTop: 'Til toppen',
    copyLink: 'Kopiér link',
    linkCopied: 'Link kopieret',
    breadcrumb: 'Brødkrummesti',
    theme: 'Tema',
    themeSystem: 'System',
    themeLight: 'Lyst',
    themeDark: 'Mørkt',
    language: 'Sprog',
    langSuggest: 'Denne side findes på dansk.',
    langSwitch: 'Skift til dansk',
    langKeep: 'Nej tak',
    notFoundTitle: 'Siden blev ikke fundet',
    notFoundBody: 'Siden, du bad om, findes ikke - den er måske flyttet.',
    notFoundHome: 'Gå til den danske forside',
    loading: 'Indlæser…',
  },
} as const;
