/**
 * Study: quizzes, progress and how-well-do-you-know-it statuses.
 * A slice of `UI` (site.ts), which merges every area into one table per language.
 */
export const UI_STUDY = {
  en: {
    studyIntro:
      'Hand-written questions, and questions generated from the map. Right answers come back later; wrong ones come back soon.',
    checkYourself: 'Check yourself',
    start: 'Start a session',
    next: 'Next',
    again: 'Another round',
    correct: 'Correct.',
    incorrect: 'Not quite - the answer is',
    readAbout: 'Read about',
    score: 'You got {n} of {m} right.',
    noQuestions: 'No questions for this term yet.',
    practise: 'Practise',
    quizMeOn: 'Quiz me on:',
    everything: 'Everything',
    weakTerms: 'My weak terms ({n})',
    clusters: 'Clusters',
    noWeakTerms:
      'No weak terms yet - terms you answer wrongly or mark as “Learning it” or “Don’t understand” gather here.',
    progress: 'Your progress',
    practised: 'Practised',
    known: 'Known',
    dueNow: 'Due for review',
    localNote: 'Your progress is stored only in this browser.',
    recommended: 'Recommended next',
    recommendedIntro: 'Terms whose prerequisites you already know.',
    statusQuestion: 'How well do you know this?',
    status_know: 'I know it',
    status_familiar: 'Familiar',
    status_learning: 'Learning it',
    status_unknown: "Don't understand",
  },
  da: {
    studyIntro:
      'Håndskrevne spørgsmål og spørgsmål genereret ud fra kortet. Rigtige svar vender tilbage senere; forkerte vender snart tilbage.',
    checkYourself: 'Test dig selv',
    start: 'Start en runde',
    next: 'Næste',
    again: 'En runde til',
    correct: 'Rigtigt.',
    incorrect: 'Ikke helt - svaret er',
    readAbout: 'Læs om',
    score: 'Du fik {n} af {m} rigtige.',
    noQuestions: 'Ingen spørgsmål til dette begreb endnu.',
    practise: 'Træn',
    quizMeOn: 'Quiz mig i:',
    everything: 'Det hele',
    weakTerms: 'Mine svage begreber ({n})',
    clusters: 'Klynger',
    noWeakTerms:
      'Ingen svage begreber endnu - begreber, du svarer forkert på eller markerer som “Lærer det” eller “Forstår det ikke”, samles her.',
    progress: 'Dine fremskridt',
    practised: 'Øvet',
    known: 'Kendt',
    dueNow: 'Klar til repetition',
    localNote: 'Dine fremskridt gemmes kun i denne browser.',
    recommended: 'Anbefalet som det næste',
    recommendedIntro: 'Begreber, hvis forudsætninger du allerede kender.',
    statusQuestion: 'Hvor godt kender du dette?',
    status_know: 'Kender det',
    status_familiar: 'Bekendt',
    status_learning: 'Lærer det',
    status_unknown: 'Forstår det ikke',
  },
} as const;
