export const LANGS = ['en', 'da'] as const;
export type Lang = (typeof LANGS)[number];

const rawBase = import.meta.env.BASE_URL;
/** Always ends in '/'. GitHub Pages serves the site under /tech-atlas/. */
export const BASE = rawBase.endsWith('/') ? rawBase : `${rawBase}/`;

/** Base-path-aware URL for an internal path. */
export const url = (path = '') => BASE + path.replace(/^\//, '');

/**
 * Accounts + synced progress (A44) exist only when the build is given a Supabase
 * project. Without these two public values every account surface is left out and
 * the site is exactly the local-only one.
 */
export const SUPABASE_URL: string = import.meta.env.PUBLIC_SUPABASE_URL ?? '';
export const SUPABASE_ANON_KEY: string = import.meta.env.PUBLIC_SUPABASE_ANON_KEY ?? '';
export const ACCOUNTS = !!SUPABASE_URL && !!SUPABASE_ANON_KEY;

export const termUrl = (lang: Lang, id: string) => url(`${lang}/terms/${id}/`);

/** Swap the language segment of the current pathname. */
export const swapLang = (pathname: string, to: Lang) =>
  pathname.startsWith(BASE + 'en') || pathname.startsWith(BASE + 'da')
    ? BASE + to + pathname.slice(BASE.length + 2)
    : url(`${to}/`);

export const UI = {
  en: {
    tagline: 'A bilingual technical dictionary that reads as a knowledge graph.',
    index: 'Index',
    compare: 'Compare',
    study: 'Study',
    studyIntro:
      'Questions generated from the map. Right answers come back later; wrong ones come back soon.',
    checkYourself: 'Check yourself',
    start: 'Start a session',
    next: 'Next',
    again: 'Another round',
    correct: 'Correct.',
    incorrect: 'Not quite — the answer is',
    score: 'You got {n} of {m} right.',
    noQuestions: 'No questions for this term yet.',
    practise: 'Practise',
    allTerms: 'All terms',
    progress: 'Your progress',
    practised: 'Practised',
    known: 'Known',
    dueNow: 'Due for review',
    localNote: 'Your progress is stored only in this browser.',
    recommended: 'Recommended next',
    recommendedIntro: 'Terms whose prerequisites you already know.',
    statusQuestion: 'How well do you know this?',
    status_know: 'I know it',
    status_familiar: 'Familiar',
    status_learning: 'Learning it',
    status_unknown: "Don't understand",
    colourBy: 'Colour by',
    byCluster: 'Cluster',
    byKnowledge: 'My knowledge',
    intentCompare: 'Compare {a} and {b}',
    intentRoute: 'Show the route from {a} to {b}',
    intentBefore: 'What to learn before {a}',
    review: 'Review queue',
    reviewIntro:
      'Every entry was drafted by an AI and stays marked as a draft until a person has checked it. To approve one, open it on GitHub and change draft: true to draft: false.',
    reviewed: 'reviewed',
    editOnGitHub: 'Edit on GitHub',
    sourceCode: 'Source',
    explorer: 'Explorer',
    neighbourhood: 'Neighbourhood',
    expand: 'Expand +1',
    wholeMap: 'Whole map',
    explorerIntro: 'The whole map. Click a term to see it; double-click to open its entry.',
    layoutForce: 'Force',
    layoutDepth: 'By depth',
    depthNote: 'Height = depth: foundations at the bottom, advanced terms on top.',
    domains: 'Domains',
    relationshipTypes: 'Relationships',
    route: 'Route between two terms',
    from: 'From',
    to: 'To',
    findRoute: 'Find route',
    noRoute: 'No route found.',
    showPrerequisites: 'Show prerequisites',
    openEntry: 'Open entry',
    clear: 'Clear',
    learnFirst: 'What to learn first',
    learnFirstIntro: 'Everything this builds on, foundations first.',
    openExplorer: 'Open in the explorer →',
    loading: 'Loading…',
    search: 'Search terms, aliases, definitions…',
    noResults: 'No matches',
    connections: 'Connections',
    relationships: 'Relationships',
    mentionedIn: 'Mentioned in',
    sources: 'Sources',
    aka: 'Also known as',
    readArticle: 'Read the full article →',
    backToTerm: '← Back to the entry',
    draft: 'Draft — this entry has not been reviewed yet.',
    compareTitle: "Don't confuse these",
    compareIntro: 'Pairs that are easy to mix up, side by side.',
    whyDiffer: 'Why they differ',
    shared: 'Shared connections',
    versus: 'vs',
    terms: 'terms',
    formal: 'Formal',
    plain: 'In plain English',
    inPractice: 'In practice',
    whyItMatters: 'Why it matters',
    timeline: 'Timeline',
    timelineIntro:
      'Terms by the decade they entered use. Colour = cluster; click a term to open it.',
    undatedNote: '{n} terms have no year yet and are not shown.',
    undatedNoteOne: '1 term has no year yet and is not shown.',
    noDated: 'No terms have a year yet.',
    allDomains: 'All',
    decade: '{d}s',
    layoutTime: 'By time',
    timeNote: 'Left to right = the year a term entered use. Terms without a year sit on the left.',
    account: 'Account',
    signIn: 'Sign in',
    signOut: 'Sign out',
    accountIntro:
      'Sign in to keep your progress in step across devices. Everything works without an account too.',
    accountsOff: 'Accounts are not enabled on this site. Your progress is stored in this browser.',
    emailLabel: 'Email',
    sendLink: 'Email me a sign-in link',
    linkSent: 'Check your inbox and open the link in this browser to finish signing in.',
    or: 'or',
    withGitHub: 'Sign in with GitHub',
    authError: 'Something went wrong: {msg}',
    signedInAs: 'Signed in as {email}',
    syncNow: 'Sync now',
    sync_syncing: 'Syncing…',
    sync_synced: 'Progress synced.',
    sync_offline: 'Offline — changes are kept here and sync when you are back online.',
    sync_error: 'Could not sync just now — your progress is safe in this browser.',
    lastSynced: 'Progress synced at {time}.',
    deleteData: 'Delete my synced data',
    deleteNote:
      'Deletes your synced progress from the server and signs you out; other devices are signed out at their next sync. Progress in this browser is kept.',
    deleteConfirm: 'Delete your synced progress from the server and sign out?',
    deleted: 'Your synced data has been deleted.',
    syncNote: 'Your progress is stored in this browser — sign in to sync it across devices.',
    stoppedNote:
      'Your synced data was deleted, so syncing is paused. Start again to upload the progress in this browser.',
    startAgain: 'Start syncing again',
    remoteDeleted:
      'You were signed out because your synced data was deleted on another device. Progress in this browser is kept.',
    dismiss: 'Dismiss',
    signOutFailed: 'Your data was deleted, but signing out other devices failed: {msg}',
  },
  da: {
    tagline: 'En tosproget teknisk ordbog, der læses som en vidensgraf.',
    index: 'Indeks',
    compare: 'Sammenlign',
    study: 'Øv',
    studyIntro:
      'Spørgsmål genereret ud fra kortet. Rigtige svar vender tilbage senere; forkerte vender snart tilbage.',
    checkYourself: 'Test dig selv',
    start: 'Start en runde',
    next: 'Næste',
    again: 'En runde til',
    correct: 'Rigtigt.',
    incorrect: 'Ikke helt — svaret er',
    score: 'Du fik {n} af {m} rigtige.',
    noQuestions: 'Ingen spørgsmål til dette begreb endnu.',
    practise: 'Øv',
    allTerms: 'Alle begreber',
    progress: 'Dine fremskridt',
    practised: 'Øvet',
    known: 'Kendt',
    dueNow: 'Klar til repetition',
    localNote: 'Dine fremskridt gemmes kun i denne browser.',
    recommended: 'Anbefalet som det næste',
    recommendedIntro: 'Begreber, hvis forudsætninger du allerede kender.',
    statusQuestion: 'Hvor godt kender du dette?',
    status_know: 'Kender det',
    status_familiar: 'Bekendt',
    status_learning: 'Lærer det',
    status_unknown: 'Forstår det ikke',
    colourBy: 'Farv efter',
    byCluster: 'Klynge',
    byKnowledge: 'Min viden',
    intentCompare: 'Sammenlign {a} og {b}',
    intentRoute: 'Vis vejen fra {a} til {b}',
    intentBefore: 'Hvad du bør lære før {a}',
    review: 'Gennemgangskø',
    reviewIntro:
      'Alle opslag er udkast skrevet af en AI og forbliver markeret som kladde, indtil et menneske har tjekket dem. Godkend et opslag ved at åbne det på GitHub og ændre draft: true til draft: false.',
    reviewed: 'gennemgået',
    editOnGitHub: 'Redigér på GitHub',
    sourceCode: 'Kildekode',
    explorer: 'Udforsk',
    neighbourhood: 'Nabolag',
    expand: 'Udvid +1',
    wholeMap: 'Hele kortet',
    explorerIntro:
      'Hele kortet. Klik på et begreb for at se det; dobbeltklik for at åbne opslaget.',
    layoutForce: 'Kraft',
    layoutDepth: 'Efter dybde',
    depthNote: 'Højde = dybde: grundlaget nederst, avancerede begreber øverst.',
    domains: 'Domæner',
    relationshipTypes: 'Relationer',
    route: 'Vej mellem to begreber',
    from: 'Fra',
    to: 'Til',
    findRoute: 'Find vej',
    noRoute: 'Ingen vej fundet.',
    showPrerequisites: 'Vis forudsætninger',
    openEntry: 'Åbn opslag',
    clear: 'Ryd',
    learnFirst: 'Hvad du bør lære først',
    learnFirstIntro: 'Alt det, dette bygger på — grundlaget først.',
    openExplorer: 'Åbn i udforskeren →',
    loading: 'Indlæser…',
    search: 'Søg i begreber, synonymer, definitioner…',
    noResults: 'Ingen resultater',
    connections: 'Forbindelser',
    relationships: 'Relationer',
    mentionedIn: 'Nævnt i',
    sources: 'Kilder',
    aka: 'Også kendt som',
    readArticle: 'Læs hele artiklen →',
    backToTerm: '← Tilbage til opslaget',
    draft: 'Kladde — dette opslag er endnu ikke gennemgået.',
    compareTitle: 'Forveksl ikke disse',
    compareIntro: 'Begrebspar, der er lette at blande sammen, side om side.',
    whyDiffer: 'Hvorfor de er forskellige',
    shared: 'Fælles forbindelser',
    versus: 'vs.',
    terms: 'begreber',
    formal: 'Formelt',
    plain: 'Forklaret enkelt',
    inPractice: 'I praksis',
    whyItMatters: 'Hvorfor det betyder noget',
    timeline: 'Tidslinje',
    timelineIntro:
      'Begreber efter det årti, de kom i brug. Farve = klynge; klik på et begreb for at åbne det.',
    undatedNote: '{n} begreber har endnu intet årstal og vises ikke.',
    undatedNoteOne: '1 begreb har endnu intet årstal og vises ikke.',
    noDated: 'Ingen begreber har et årstal endnu.',
    allDomains: 'Alle',
    decade: "{d}'erne",
    layoutTime: 'Efter tid',
    timeNote:
      'Fra venstre mod højre = året, et begreb kom i brug. Begreber uden årstal står til venstre.',
    account: 'Konto',
    signIn: 'Log ind',
    signOut: 'Log ud',
    accountIntro:
      'Log ind for at holde dine fremskridt ens på tværs af enheder. Alt virker også uden en konto.',
    accountsOff: 'Konti er ikke slået til på dette site. Dine fremskridt gemmes i denne browser.',
    emailLabel: 'E-mail',
    sendLink: 'Send mig et login-link',
    linkSent: 'Tjek din indbakke, og åbn linket i denne browser for at logge ind.',
    or: 'eller',
    withGitHub: 'Log ind med GitHub',
    authError: 'Noget gik galt: {msg}',
    signedInAs: 'Logget ind som {email}',
    syncNow: 'Synkronisér nu',
    sync_syncing: 'Synkroniserer …',
    sync_synced: 'Fremskridt synkroniseret.',
    sync_offline: 'Offline — ændringer gemmes her og synkroniseres, når du er online igen.',
    sync_error: 'Kunne ikke synkronisere lige nu — dine fremskridt er sikre i denne browser.',
    lastSynced: 'Fremskridt synkroniseret kl. {time}.',
    deleteData: 'Slet mine synkroniserede data',
    deleteNote:
      'Sletter dine synkroniserede fremskridt fra serveren og logger dig ud; andre enheder logges ud ved deres næste synkronisering. Fremskridt i denne browser bevares.',
    deleteConfirm: 'Slet dine synkroniserede fremskridt fra serveren og log ud?',
    deleted: 'Dine synkroniserede data er slettet.',
    syncNote:
      'Dine fremskridt gemmes i denne browser — log ind for at synkronisere dem på tværs af enheder.',
    stoppedNote:
      'Dine synkroniserede data er slettet, så synkroniseringen er sat på pause. Start igen for at uploade fremskridtene i denne browser.',
    startAgain: 'Start synkronisering igen',
    remoteDeleted:
      'Du blev logget ud, fordi dine synkroniserede data blev slettet på en anden enhed. Fremskridt i denne browser bevares.',
    dismiss: 'Luk',
    signOutFailed: 'Dine data er slettet, men det lykkedes ikke at logge andre enheder ud: {msg}',
  },
} as const;

export const DOMAIN_LABELS: Record<string, Record<Lang, string>> = {
  security: { en: 'Security', da: 'Sikkerhed' },
  cs: { en: 'Computer science', da: 'Datalogi' },
  ai: { en: 'AI', da: 'AI' },
  platform: { en: 'Platform', da: 'Platform' },
};

export const CLUSTER_LABELS: Record<string, Record<Lang, string>> = {
  fundamentals: { en: 'Fundamentals', da: 'Grundbegreber' },
  awareness: { en: 'People, culture & awareness', da: 'Mennesker, kultur og awareness' },
  controls: { en: 'Controls & technical basics', da: 'Kontroller og tekniske grundbegreber' },
  'risk-management': { en: 'Risk management', da: 'Risikostyring' },
  compliance: { en: 'Compliance & regulation', da: 'Compliance, styring og lovgivning' },
  'incident-response': { en: 'Incidents & continuity', da: 'Beredskab og hændelser' },
  networking: { en: 'Networking', da: 'Netværk' },
  os: { en: 'Operating systems', da: 'Styresystemer' },
  identity: { en: 'Identity & access', da: 'Identitet og adgang' },
  cryptography: { en: 'Cryptography', da: 'Kryptografi' },
  'ml-fundamentals': { en: 'Machine learning basics', da: 'Grundlæggende maskinlæring' },
  llm: { en: 'Language models', da: 'Sprogmodeller' },
  'ai-risk': { en: 'AI risk & governance', da: 'AI-risiko og governance' },
  cloud: { en: 'Cloud', da: 'Cloud' },
  containers: { en: 'Containers & orchestration', da: 'Containere og orkestrering' },
  delivery: { en: 'Software delivery', da: 'Softwarelevering' },
  observability: { en: 'Observability', da: 'Observerbarhed' },
};

export const CLUSTER_COLOURS: Record<string, string> = {
  fundamentals: '#f59e0b',
  awareness: '#ec4899',
  controls: '#22c55e',
  'risk-management': '#ef4444',
  compliance: '#a855f7',
  'incident-response': '#f97316',
  networking: '#3b82f6',
  os: '#06b6d4',
  identity: '#14b8a6',
  cryptography: '#6366f1',
  'ml-fundamentals': '#e879f9',
  llm: '#d946ef',
  'ai-risk': '#be185d',
  cloud: '#38bdf8',
  containers: '#0ea5e9',
  delivery: '#84cc16',
  observability: '#eab308',
};

export const FAMILY_COLOURS: Record<string, string> = {
  structure: '#a3a3a3',
  dependency: '#fbbf24',
  contrast: '#f472b6',
  security: '#f87171',
  regulation: '#c084fc',
  lineage: '#94a3b8',
  association: '#60a5fa',
};

export const FAMILY_LABELS: Record<string, Record<Lang, string>> = {
  structure: { en: 'Structure (kind of, part of)', da: 'Struktur (slags, del af)' },
  dependency: { en: 'Prerequisites', da: 'Forudsætninger' },
  contrast: { en: 'Contrasts & alternatives', da: 'Kontraster og alternativer' },
  security: { en: 'Attacks & defences', da: 'Angreb og forsvar' },
  regulation: { en: 'Regulation', da: 'Regulering' },
  lineage: { en: 'Lineage', da: 'Afstamning' },
  association: { en: 'Used together', da: 'Bruges sammen' },
};

/** Where the source lives — used for 'Edit on GitHub' links in the review queue. */
export const REPO = 'https://github.com/CMaintz/tech-atlas';
