export const LANGS = ['en', 'da'] as const;
export type Lang = (typeof LANGS)[number];

const rawBase = import.meta.env.BASE_URL;
/** Always ends in '/'. GitHub Pages serves the site under /tech-atlas/. */
export const BASE = rawBase.endsWith('/') ? rawBase : `${rawBase}/`;

/** Base-path-aware URL for an internal path. */
export const url = (path = '') => BASE + path.replace(/^\//, '');

export const termUrl = (lang: Lang, id: string) => url(`${lang}/terms/${id}/`);

/** Swap the language segment of the current pathname. */
export const swapLang = (pathname: string, to: Lang) =>
  pathname.startsWith(BASE + 'en') || pathname.startsWith(BASE + 'da')
    ? BASE + to + pathname.slice(BASE.length + 2)
    : url(`${to}/`);

export const UI = {
  en: {
    tagline: 'A bilingual technical dictionary that reads as a knowledge graph.',
    index: 'Index',
    compare: 'Compare',
    study: 'Study',
    studyIntro:
      'Questions generated from the map. Right answers come back later; wrong ones come back soon.',
    checkYourself: 'Check yourself',
    start: 'Start a session',
    next: 'Next',
    again: 'Another round',
    correct: 'Correct.',
    incorrect: 'Not quite — the answer is',
    score: 'You got {n} of {m} right.',
    noQuestions: 'No questions for this term yet.',
    practise: 'Practise',
    allTerms: 'All terms',
    progress: 'Your progress',
    practised: 'Practised',
    known: 'Known',
    dueNow: 'Due for review',
    localNote: 'Your progress is stored only in this browser.',
    recommended: 'Recommended next',
    recommendedIntro: 'Terms whose prerequisites you already know.',
    statusQuestion: 'How well do you know this?',
    status_know: 'I know it',
    status_familiar: 'Familiar',
    status_learning: 'Learning it',
    status_unknown: "Don't understand",
    colourBy: 'Colour by',
    byCluster: 'Cluster',
    byKnowledge: 'My knowledge',
    explorer: 'Explorer',
    neighbourhood: 'Neighbourhood',
    expand: 'Expand +1',
    wholeMap: 'Whole map',
    explorerIntro: 'The whole map. Click a term to see it; double-click to open its entry.',
    layoutForce: 'Force',
    layoutDepth: 'By depth',
    depthNote: 'Height = depth: foundations at the bottom, advanced terms on top.',
    domains: 'Domains',
    relationshipTypes: 'Relationships',
    route: 'Route between two terms',
    from: 'From',
    to: 'To',
    findRoute: 'Find route',
    noRoute: 'No route found.',
    showPrerequisites: 'Show prerequisites',
    openEntry: 'Open entry',
    clear: 'Clear',
    learnFirst: 'What to learn first',
    learnFirstIntro: 'Everything this builds on, foundations first.',
    openExplorer: 'Open in the explorer →',
    loading: 'Loading…',
    search: 'Search terms, aliases, definitions…',
    noResults: 'No matches',
    connections: 'Connections',
    relationships: 'Relationships',
    sources: 'Sources',
    aka: 'Also known as',
    readArticle: 'Read the full article →',
    backToTerm: '← Back to the entry',
    draft: 'Draft — this entry has not been reviewed yet.',
    compareTitle: "Don't confuse these",
    compareIntro: 'Pairs that are easy to mix up, side by side.',
    whyDiffer: 'Why they differ',
    shared: 'Shared connections',
    versus: 'vs',
    terms: 'terms',
    formal: 'Formal',
    plain: 'In plain English',
    inPractice: 'In practice',
    whyItMatters: 'Why it matters',
  },
  da: {
    tagline: 'En tosproget teknisk ordbog, der læses som en vidensgraf.',
    index: 'Indeks',
    compare: 'Sammenlign',
    study: 'Øv',
    studyIntro:
      'Spørgsmål genereret ud fra kortet. Rigtige svar vender tilbage senere; forkerte vender snart tilbage.',
    checkYourself: 'Test dig selv',
    start: 'Start en runde',
    next: 'Næste',
    again: 'En runde til',
    correct: 'Rigtigt.',
    incorrect: 'Ikke helt — svaret er',
    score: 'Du fik {n} af {m} rigtige.',
    noQuestions: 'Ingen spørgsmål til dette begreb endnu.',
    practise: 'Øv',
    allTerms: 'Alle begreber',
    progress: 'Dine fremskridt',
    practised: 'Øvet',
    known: 'Kendt',
    dueNow: 'Klar til repetition',
    localNote: 'Dine fremskridt gemmes kun i denne browser.',
    recommended: 'Anbefalet som det næste',
    recommendedIntro: 'Begreber, hvis forudsætninger du allerede kender.',
    statusQuestion: 'Hvor godt kender du dette?',
    status_know: 'Kender det',
    status_familiar: 'Bekendt',
    status_learning: 'Lærer det',
    status_unknown: 'Forstår det ikke',
    colourBy: 'Farv efter',
    byCluster: 'Klynge',
    byKnowledge: 'Min viden',
    explorer: 'Udforsk',
    neighbourhood: 'Nabolag',
    expand: 'Udvid +1',
    wholeMap: 'Hele kortet',
    explorerIntro:
      'Hele kortet. Klik på et begreb for at se det; dobbeltklik for at åbne opslaget.',
    layoutForce: 'Kraft',
    layoutDepth: 'Efter dybde',
    depthNote: 'Højde = dybde: grundlaget nederst, avancerede begreber øverst.',
    domains: 'Domæner',
    relationshipTypes: 'Relationer',
    route: 'Vej mellem to begreber',
    from: 'Fra',
    to: 'Til',
    findRoute: 'Find vej',
    noRoute: 'Ingen vej fundet.',
    showPrerequisites: 'Vis forudsætninger',
    openEntry: 'Åbn opslag',
    clear: 'Ryd',
    learnFirst: 'Hvad du bør lære først',
    learnFirstIntro: 'Alt det, dette bygger på — grundlaget først.',
    openExplorer: 'Åbn i udforskeren →',
    loading: 'Indlæser…',
    search: 'Søg i begreber, synonymer, definitioner…',
    noResults: 'Ingen resultater',
    connections: 'Forbindelser',
    relationships: 'Relationer',
    sources: 'Kilder',
    aka: 'Også kendt som',
    readArticle: 'Læs hele artiklen →',
    backToTerm: '← Tilbage til opslaget',
    draft: 'Kladde — dette opslag er endnu ikke gennemgået.',
    compareTitle: 'Forveksl ikke disse',
    compareIntro: 'Begrebspar, der er lette at blande sammen, side om side.',
    whyDiffer: 'Hvorfor de er forskellige',
    shared: 'Fælles forbindelser',
    versus: 'vs.',
    terms: 'begreber',
    formal: 'Formelt',
    plain: 'Forklaret enkelt',
    inPractice: 'I praksis',
    whyItMatters: 'Hvorfor det betyder noget',
  },
} as const;

export const DOMAIN_LABELS: Record<string, Record<Lang, string>> = {
  security: { en: 'Security', da: 'Sikkerhed' },
  cs: { en: 'Computer science', da: 'Datalogi' },
  ai: { en: 'AI', da: 'AI' },
  platform: { en: 'Platform', da: 'Platform' },
};

export const CLUSTER_LABELS: Record<string, Record<Lang, string>> = {
  fundamentals: { en: 'Fundamentals', da: 'Grundbegreber' },
  awareness: { en: 'People, culture & awareness', da: 'Mennesker, kultur og awareness' },
  controls: { en: 'Controls & technical basics', da: 'Kontroller og tekniske grundbegreber' },
  'risk-management': { en: 'Risk management', da: 'Risikostyring' },
  compliance: { en: 'Compliance & regulation', da: 'Compliance, styring og lovgivning' },
  'incident-response': { en: 'Incidents & continuity', da: 'Beredskab og hændelser' },
  networking: { en: 'Networking', da: 'Netværk' },
  os: { en: 'Operating systems', da: 'Styresystemer' },
  identity: { en: 'Identity & access', da: 'Identitet og adgang' },
  cryptography: { en: 'Cryptography', da: 'Kryptografi' },
};

export const CLUSTER_COLOURS: Record<string, string> = {
  fundamentals: '#f59e0b',
  awareness: '#ec4899',
  controls: '#22c55e',
  'risk-management': '#ef4444',
  compliance: '#a855f7',
  'incident-response': '#f97316',
  networking: '#3b82f6',
  os: '#06b6d4',
  identity: '#14b8a6',
  cryptography: '#6366f1',
};

export const FAMILY_COLOURS: Record<string, string> = {
  structure: '#a3a3a3',
  dependency: '#fbbf24',
  contrast: '#f472b6',
  security: '#f87171',
  regulation: '#c084fc',
  lineage: '#94a3b8',
  association: '#60a5fa',
};

export const FAMILY_LABELS: Record<string, Record<Lang, string>> = {
  structure: { en: 'Structure (kind of, part of)', da: 'Struktur (slags, del af)' },
  dependency: { en: 'Prerequisites', da: 'Forudsætninger' },
  contrast: { en: 'Contrasts & alternatives', da: 'Kontraster og alternativer' },
  security: { en: 'Attacks & defences', da: 'Angreb og forsvar' },
  regulation: { en: 'Regulation', da: 'Regulering' },
  lineage: { en: 'Lineage', da: 'Afstamning' },
  association: { en: 'Used together', da: 'Bruges sammen' },
};
